# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install modules
              run: |
                  npm i --include=dev

            - name: Run linting check
              run: |
                  npm run lint:check

            - name: Run formatting check
              run: |
                  npm run format:check

    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install modules
              run: |
                  npm i

            - name: Run tests
              run: |
                  npm run test
